name: Validate Example Configurations

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  process-examples:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install preCICE
      run: |
        sudo apt update
        sudo apt install -y libboost-dev
        wget https://github.com/precice/precice/releases/download/v3.1.2/libprecice3_3.1.2_noble.deb
        sudo apt install -y ./libprecice3_3.1.2_noble.deb

    - name: Test precice-tools
      run: |
        which precice-tools
        precice-tools version
    - name: Test precice-tools in a clean environment
      run: |
        env -i bash --noprofile --norc
        which precice-tools
        precice-tools version
