name: Validate Example Configurations

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  discover-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout config-checker
      uses: actions/checkout@v4
      with:
        repository: precice-forschungsprojekt/config-checker
        path: config-checker

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install .
        cd config-checker
        pip install .
    - name: Test CLI
      run: |
        source venv/bin/activate
        precice-gen --help
        cd config-checker
        python preciceconfigchecker/cli.py --help


