name: Validate Example Configurations

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  process-examples:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install preCICE
      run: |
        sudo apt update
        sudo apt install -y libboost-dev libboost-log-dev
        wget https://github.com/precice/precice/releases/download/v3.2.0/libprecice3_3.2.0_noble.deb
        sudo apt install -y ./libprecice3_3.2.0_noble.deb

    - name : TTT
      run: |
        ldconfig -p | grep libboost_log_setup

    - name: Test precice-tools
      run: |
        which precice-tools
        precice-tools version
    - name: Test precice-tools in a clean environment
      run: |
        env -i PATH=/usr/bin:/usr/local/bin bash --noprofile --norc -c 'which precice-tools; precice-tools version'

